import { useEffect, useRef } from 'react';
import { X } from 'lucide-react';
import { motion } from 'framer-motion';
import type { Project } from '../data/projects';
export default function ProjectCaseStudy({project,close}:{project:Project;close:()=>void}) {
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const el=dialog.current!;const previous=document.activeElement as HTMLElement;const scrollPosition=window.scrollY;el.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{el.close();document.body.style.overflow=overflow;previous?.focus({preventScroll:true});window.scrollTo({top:scrollPosition,behavior:'instant'})}},[]);
 return <dialog ref={dialog} onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}} aria-labelledby="case-title"><motion.article initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="case-content"><button className="icon-button close-case" onClick={close} aria-label="Close case study" autoFocus><X/></button><span className="eyebrow">Project details / {project.category}</span><h2 id="case-title">{project.title}</h2><h3>Overview</h3><p>{project.description}</p><img className="case-image" src={project.image} alt={`${project.title} illustrative preview, not a production screenshot`}/><p className="micro">Illustrative project preview</p>{[['Problem',project.problem],['Solution',project.solution],['Development process',project.process],['Challenges',project.challenges],['Results',project.results]].map(([title,value])=><section key={title}><h3>{title}</h3><p>{value||'Details to be added.'}</p></section>)}<h3>Features</h3><ul>{project.features.map(x=><li key={x}>{x}</li>)}</ul><h3>Technology</h3><div className="tags">{project.technologies.map(x=><span key={x}>{x}</span>)}</div><div className="actions">{project.live&&<a className="button primary" href={project.live} target="_blank" rel="noreferrer">Live website</a>}{project.github&&<a className="button" href={project.github} target="_blank" rel="noreferrer">GitHub</a>}</div></motion.article></dialog>;
}
