import { useState, useEffect, type ReactNode, type FormEvent } from 'react';
import { AnimatePresence, motion, MotionConfig } from 'framer-motion';
import { Sun, Moon, Menu, X, Github, Linkedin, Download, Code2, Layers, Sparkles, Globe, Atom, Terminal, GraduationCap, Mail, Braces, GitBranch, Cpu } from 'lucide-react';
import { site } from './config/site';
import { skills } from './data/skills';
import { experience } from './data/experience';
import { type Project } from './data/projects';
import Projects from './components/Projects';
import ProjectCaseStudy from './components/ProjectCaseStudy';

const nav=['About','Skills','Experience','Projects','Services','Contact'];
function Reveal({children,className=''}:{children:ReactNode;className?:string}){return <motion.div className={className} initial={{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.08}} transition={{duration:.6}}>{children}</motion.div>}
function SectionTitle({number,children}:{number:string;children:ReactNode}){return <div className="section-title"><span className="eyebrow">/{number}</span><h2>{children}</h2><span className="section-line"/></div>}
function SocialLinks(){return <>{site.github&&<a aria-label="GitHub" href={site.github} target="_blank" rel="noreferrer"><Github size={19}/></a>}{site.linkedin&&<a aria-label="LinkedIn" href={site.linkedin} target="_blank" rel="noreferrer"><Linkedin size={19}/></a>}</>}
function TechIcon({name}:{name:string}){if(name==='React')return <Atom/>;if(name==='Git'||name==='GitHub')return name==='Git'?<GitBranch/>:<Github/>;if(name.includes('API'))return <Sparkles/>;if(name==='Python')return <Terminal/>;if(name==='Tailwind CSS')return <span>≈</span>;return <span>{({TypeScript:'TS',JavaScript:'JS',HTML5:'H5',CSS3:'C3',Vite:'V'} as Record<string,string>)[name]||'{}'}</span>}
function App(){
 const [theme,setTheme]=useState(()=>document.documentElement.dataset.theme||'dark');
 const [menu,setMenu]=useState(false),[selected,setSelected]=useState<Project|null>(null),[formStatus,setFormStatus]=useState('');
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('mu-theme',theme)}catch{}},[theme]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 const toggle=<button className="icon-button theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button>;
 const resumeButton=<a className="resume-button" href="#contact" aria-label="View resume"><Download size={14}/><span>Resume</span></a>;
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!site.email){setFormStatus('Contact is not connected yet. Please check back once an email address has been added.');return}const data=new FormData(e.currentTarget);window.location.href=`mailto:${site.email}?subject=${encodeURIComponent('Portfolio enquiry from '+data.get('name'))}&body=${encodeURIComponent(data.get('message')+'\n\nReply to: '+data.get('email'))}`;setFormStatus('Your email app will open with a draft. Send it there to complete your message.');}
 return <MotionConfig reducedMotion="user"><a className="skip-link" href="#main">Skip to content</a><header><a href="#home" className="wordmark" aria-label="Muhammad Usama home">MU<span>.</span></a><nav className="desktop-nav" aria-label="Main navigation">{nav.map(n=><a href={'#'+n.toLowerCase()} key={n}>{n}</a>)}</nav><div className="header-actions"><SocialLinks/>{resumeButton}{toggle}<button className="icon-button menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-controls="mobile-nav" aria-label={menu?'Close menu':'Open menu'}>{menu?<X/>:<Menu/>}</button></div></header>
 <AnimatePresence>{menu&&<motion.nav id="mobile-nav" className="mobile-nav" initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} aria-label="Mobile navigation">{nav.map((n,i)=><a key={n} href={'#'+n.toLowerCase()} onClick={()=>setMenu(false)}><small>0{i+1}</small>{n}</a>)}<div className="mobile-theme">Appearance {toggle}</div></motion.nav>}</AnimatePresence>
 <main id="main"><section className="hero wrap" id="home"><div className="hero-inner"><Reveal className="hero-copy-panel"><div className="hero-meta"><span className="availability"><i/> Available for opportunities</span></div><h1 className="hero-name"><span className="name-accent">MUHAMMAD</span><span className="name-dark">USAMA.</span></h1><div className="hero-role">Frontend Developer</div><div className="hero-stack">React / TypeScript / JavaScript / AI</div><p className="hero-description">I&apos;m a frontend developer who enjoys building responsive web applications and AI-powered products. I focus on clean interfaces, useful features, and great user experiences.</p><div className="hero-actions"><a className="button primary" href="#projects">View My Work</a><a className="button secondary" href="#contact">Contact Me</a></div></Reveal><Reveal className="hero-visual-panel"><div className="hero-visual"><div className="visual-badge">[ IDEAS INTO INTERFACES ]</div><div className="visual-shell"><div className="visual-orb orb-one"/><div className="visual-orb orb-two"/><div className="visual-grid"/><div className="visual-card"><span>{'const developer = {'}</span><span>{'name: "Muhammad Usama",'}</span><span>{'role: "Frontend Developer",'}</span><span>{'stack: ["React", "TypeScript"],'}</span><span>{'building: "Web & AI",'}</span><span>{'approach: "Clean. Responsive."'}</span><span>{'};'}</span></div></div><div className="visual-footer">CREATIVE CODE. DIGITAL EXPERIENCES.</div></div></Reveal></div><div className="hero-footer"><a href="#about" className="scroll-explore">Scroll to explore ↓</a></div></section>
 <section className="wrap section" id="about"><SectionTitle number="01">ABOUT ME</SectionTitle><Reveal><p className="manifesto">Good code starts with<br/><span>understanding people.</span></p><div className="about-grid"><span className="eyebrow">This is me.</span><div><h3>Hi, I’m Usama.</h3><p>I’m a Web/Frontend Developer focused on building modern, responsive and user-friendly web applications. I work primarily with React, TypeScript and JavaScript, and I also build AI-powered products by integrating services such as Gemini and Claude APIs.</p><p>With a BSIT background at Virtual University, my work connects frontend development with practical web applications and SaaS products.</p></div><div className="about-note"><Braces size={36}/><span>From the first component<br/>to the complete product.</span><small>REACT / TYPESCRIPT / AI</small></div></div></Reveal></section>
 <section className="wrap section" id="skills"><SectionTitle number="02">MY STACK</SectionTitle>{skills.map(s=><Reveal className="stack-row" key={s.category}><h3>{s.category}</h3><div className="stack-items">{s.items.map(item=><div className="tech" key={item}><span className="tech-icon"><TechIcon name={item}/></span>{item}</div>)}</div></Reveal>)}</section>
 <section className="wrap section" id="experience"><SectionTitle number="03">MY EXPERIENCE</SectionTitle>{experience.map((e,i)=><Reveal key={e.company} className="experience-row"><div className="experience-company"><span className="eyebrow">0{i+1} / {e.date||'Experience'}</span><h3>{e.company}</h3>{e.url&&<a href={e.url} target="_blank" rel="noreferrer" className="text-link">Visit website</a>}</div><div><h4>{e.role}</h4><p>{e.description}</p><ul>{e.points.map(p=><li key={p}>{p}</li>)}</ul></div></Reveal>)}</section>
 <Projects onSelect={setSelected} />
 <section className="wrap section" id="services"><SectionTitle number="05">WHAT I BUILD</SectionTitle><div className="services">{[ ['Responsive Web Applications',Globe],['React Frontends',Atom],['AI-Powered Applications',Sparkles],['SaaS Products',Layers],['Landing Pages',Code2],['API Integrations',Cpu] ].map(([name,Icon],i)=>{const ServiceIcon=Icon as typeof Globe;return <Reveal className="service" key={String(name)}><ServiceIcon size={28}/><span className="eyebrow">0{i+1}</span><h3>{String(name)}</h3></Reveal>})}</div></section>
 <section className="wrap section" id="education"><SectionTitle number="06">EDUCATION</SectionTitle><Reveal className="education"><GraduationCap size={40}/><div><h3>{site.education.degree}</h3><p>{site.education.institution}{site.education.date&&' · '+site.education.date}</p></div><span className="eyebrow">BSIT</span></Reveal></section>
 <section className="wrap github-section"><Github size={44}/><div><h2>Explore my code.</h2><p>Most of my projects are built with modern web technologies and are available on GitHub.</p></div>{site.github?<a className="button" href={site.github} target="_blank" rel="noreferrer">Visit GitHub</a>:<span className="coming-soon">GitHub link coming soon</span>}</section>
 <section className="wrap section contact" id="contact"><SectionTitle number="07">LET’S TALK</SectionTitle><div className="contact-grid"><div><h2>Have a project<br/>in <span>mind?</span></h2><p>Let’s build something useful, modern, and impactful.</p><div className="contact-links">{site.email?<a href={'mailto:'+site.email}><Mail size={18}/>{site.email}</a>:<span>Email coming soon</span>}<SocialLinks/></div></div><form onSubmit={submit}><label>Your name<input name="name" autoComplete="name" placeholder="How should I call you?" required maxLength={120}/></label><label>Email address<input name="email" type="email" autoComplete="email" placeholder="you@example.com" required maxLength={254}/></label><label>Your message<textarea name="message" rows={3} placeholder="Tell me about your project…" required maxLength={5000}/></label><button className="button primary" type="submit" disabled={!site.email}>Send message</button><p className="form-note" role="status">{formStatus||(site.email?'Opens a draft in your email app.':'Messaging will be available once contact details are added.')}</p></form></div></section>
 </main><footer className="wrap"><div className="footer-top"><a className="wordmark" href="#home">MU<span>.</span></a><span>Frontend / Web Developer</span><nav aria-label="Footer navigation">{nav.map(n=><a key={n} href={'#'+n.toLowerCase()}>{n}</a>)}</nav></div><div className="footer-name" aria-hidden="true">MUHAMMAD USAMA</div><div className="footer-bottom"><span>© 2026 Muhammad Usama. All rights reserved.</span><span>Built with React & TypeScript</span><SocialLinks/></div></footer>{selected&&<ProjectCaseStudy project={selected} close={()=>setSelected(null)}/>}</MotionConfig>
}
export default App;
